import express from 'express';
import bodyParser from 'body-parser';
import userRouter from './routers/user.router.js';
import taskRouter from './routers/task.router.js';
import aiRouter from './routers/ai.router.js';
import categoryRouter from './routers/category.router.js';
import settingRouter from './routers/setting.router.js';
import swaggerUI from 'swagger-ui-express';
import swaggerSpec from './config/swagger.js';
const app=express();
app.use(bodyParser.json());
app.use('/api/docs',swaggerUI.serve, swaggerUI.setup(swaggerSpec));
app.use('/api/user',userRouter);
app.use('/api/tasks',taskRouter);
app.use('/api/ai',aiRouter);
app.use('/api/categories',categoryRouter);
app.use('/api/uploads', express.static('uploads'));
app.use('/api/settings',settingRouter);

export default app;